version: "3.9"
services:
  backend:
    image: "youtoddler/backend:latest"
    command: java -jar youtoddler-spring-$${API_VERSION}.jar
    ports:
      - "9090:9090"
  frontend:
    image: "youtoddler/frontend:latest"
    ports:
      - "8080:80"
