/* tslint:disable */
/* eslint-disable */
/**
 * YouToddler - OpenAPI 3.0
 * This is an on-premise download manager for youtube-dlp. It should be based on the OpenAPI 3.0 specification.   _If you're looking for the sprint board, then click [here](https://manhatten.atlassian.net/jira/software/projects/MAN/boards/1)._  Some useful links: - [The YouToddler repository](https://github.com/cant0r/YouToddler) - [The backend API definition for YouToddler](https://manhatten.atlassian.net/wiki/spaces/AT/pages/6094879/YouToddler+Backend) - [The WebAPi definition for YouToddler](https://manhatten.atlassian.net/wiki/spaces/AT/pages/4063276/REST+API+interfaces)
 *
 * OpenAPI spec version: 0.2.1
 * Contact: pixelbetyar@mailbox.unideb.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HistoryLog } from '../models';
/**
 * HistoryApi - axios parameter creator
 * @export
 */
export const HistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns all history data regarding previous downloads. Could be made deprecated, and only allow specified history data to be GET later.
         * @summary Get all previous downloads' logs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllHistory: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/history/getAll`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns specific history data regarding previous downloads. The input is the specific url, we search by this between the logs. Returns all history logs that contain the specific URL.
         * @summary Return video's video or audio data
         * @param {string} url URL of the video to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUrlHistory: async (url: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'url' is not null or undefined
            if (url === null || url === undefined) {
                throw new RequiredError('url','Required parameter url was null or undefined when calling getUrlHistory.');
            }
            const localVarPath = `/history/findByUrl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (url !== undefined) {
                localVarQueryParameter['url'] = url;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a specific history log data regarding a previous download. Takes a log ID in path, and returns that specific log, if found.
         * @summary Get log by id
         * @param {number} logId The ID that needs to be fetched.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByName: async (logId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'logId' is not null or undefined
            if (logId === null || logId === undefined) {
                throw new RequiredError('logId','Required parameter logId was null or undefined when calling getUserByName.');
            }
            const localVarPath = `/history/{logId}`
                .replace(`{${"logId"}}`, encodeURIComponent(String(logId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HistoryApi - functional programming interface
 * @export
 */
export const HistoryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Returns all history data regarding previous downloads. Could be made deprecated, and only allow specified history data to be GET later.
         * @summary Get all previous downloads' logs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllHistory(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<HistoryLog>>>> {
            const localVarAxiosArgs = await HistoryApiAxiosParamCreator(configuration).getAllHistory(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Returns specific history data regarding previous downloads. The input is the specific url, we search by this between the logs. Returns all history logs that contain the specific URL.
         * @summary Return video's video or audio data
         * @param {string} url URL of the video to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUrlHistory(url: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<HistoryLog>>>> {
            const localVarAxiosArgs = await HistoryApiAxiosParamCreator(configuration).getUrlHistory(url, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Returns a specific history log data regarding a previous download. Takes a log ID in path, and returns that specific log, if found.
         * @summary Get log by id
         * @param {number} logId The ID that needs to be fetched.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserByName(logId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<HistoryLog>>> {
            const localVarAxiosArgs = await HistoryApiAxiosParamCreator(configuration).getUserByName(logId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HistoryApi - factory interface
 * @export
 */
export const HistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Returns all history data regarding previous downloads. Could be made deprecated, and only allow specified history data to be GET later.
         * @summary Get all previous downloads' logs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllHistory(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<HistoryLog>>> {
            return HistoryApiFp(configuration).getAllHistory(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns specific history data regarding previous downloads. The input is the specific url, we search by this between the logs. Returns all history logs that contain the specific URL.
         * @summary Return video's video or audio data
         * @param {string} url URL of the video to fetch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUrlHistory(url: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<HistoryLog>>> {
            return HistoryApiFp(configuration).getUrlHistory(url, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a specific history log data regarding a previous download. Takes a log ID in path, and returns that specific log, if found.
         * @summary Get log by id
         * @param {number} logId The ID that needs to be fetched.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserByName(logId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<HistoryLog>> {
            return HistoryApiFp(configuration).getUserByName(logId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HistoryApi - object-oriented interface
 * @export
 * @class HistoryApi
 * @extends {BaseAPI}
 */
export class HistoryApi extends BaseAPI {
    /**
     * Returns all history data regarding previous downloads. Could be made deprecated, and only allow specified history data to be GET later.
     * @summary Get all previous downloads' logs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoryApi
     */
    public async getAllHistory(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<HistoryLog>>> {
        return HistoryApiFp(this.configuration).getAllHistory(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Returns specific history data regarding previous downloads. The input is the specific url, we search by this between the logs. Returns all history logs that contain the specific URL.
     * @summary Return video's video or audio data
     * @param {string} url URL of the video to fetch
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoryApi
     */
    public async getUrlHistory(url: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<HistoryLog>>> {
        return HistoryApiFp(this.configuration).getUrlHistory(url, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Returns a specific history log data regarding a previous download. Takes a log ID in path, and returns that specific log, if found.
     * @summary Get log by id
     * @param {number} logId The ID that needs to be fetched.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HistoryApi
     */
    public async getUserByName(logId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<HistoryLog>> {
        return HistoryApiFp(this.configuration).getUserByName(logId, options).then((request) => request(this.axios, this.basePath));
    }
}
